name: Build KM-Transfer APK
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.0' # نسخة تتماشى مع المشاريع القديمة والجديدة

      - name: Clean and Get dependencies
        run: |
          flutter clean
          # هذا الأمر يفرك الديون القديمة
          flutter pub get --legacy-peer-deps || flutter pub get 

      - name: Build APK
        # هذا الأمر هو السحر، يتجاهل أخطاء الأيقونات والمكتبات القديمة
        run: flutter build apk --release --no-tree-shake-icons --ignore-deprecation

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: KM-Transfer-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          
